### ISSUE TITLE
Localhost failed to start

### ISSUE THREAD

**Issue by g00seded** [DasyLabs/speakerbox#118]
I wanted to test speakerbox on my macbook and when trying to run it fails to start.

I tried it on a macbook pro with different node versions from 6->9 same with NPM :-) but seems to fail at start. Any suggestions?

[NPM-START.txt](https://github.com/DasyLabs/speakerbox/files/1651222/NPM-START.txt)
[NPM-LOG.txt](https://github.com/DasyLabs/speakerbox/files/1651223/NPM-LOG.txt)

**Comment by mariusc23** [comment]
Hm, I don't see anything useful in the logs. Make sure `scripts/start.sh` is executable (`chmod u+x scripts/start.sh` should do it) and try again.

**Comment by g00seded** [comment]
nope still giving same error the permissions are fine

**Comment by mariusc23** [comment]
Do you have `nodemon` installed?
```
npm i -g nodemon
```

**Comment by g00seded** [comment]
Ahh nodemon was not running properly, ran update and new clean install now its running :) thank you very much

**Comment by mariusc23** [comment]
Glad it was resolved 😃
