### ISSUE TITLE
Server Crashed when updating schedule of already retweeted tweet

### ISSUE THREAD

**Issue by radster360** [DasyLabs/speakerbox#53]
After the retweet was done, I went to Schedule tab and tried to update the schedule time and it resulted in getting "Server 503" error on client side, eventually making the app inaccessible.

First, maybe one shouldn't be allowed to update a "single" retweeted scheduled tweet by either disabling the schedule. Or allow the user to "clone" and than set the new schedule.

**Comment by mariusc23** [comment]
I've seen this error happen before but I'm never able to reproduce. I'm still not able to reproduce with the steps you provided. I get a different error (which I fixed just now). I suspect there is a bug in [sequelize](https://github.com/sequelize/sequelize). I added some code to try to prevent the app from blowing up.
