### ISSUE TITLE
Homepage viewed tracker is calculating incorrectly

### ISSUE THREAD

**Issue by aakashhdesai** [DasyLabs/speakerbox#77]
There isn't a 1:1 match with Google Analytics (it's about 10:1 difference between Mixpanel:GA). I can still do calculations, but would like to have an accurate cross-compare between the 2 systems.

**Comment by aakashhdesai** [comment]
Still getting really high counts of homepage viewed. Not sure what's going on.

**Comment by mariusc23** [comment]
Can you add me to GA?

**Comment by aakashhdesai** [comment]
Done

**Comment by aakashhdesai** [comment]
Working great!
